services:
  - type: web
    name: asdp
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0: app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
